---
Name: genie_admin_config
---
ModelAdmin:
  extensions:
    - ScriptGenieAdminExtension

Injector:
  ScriptGenieAdminExtension:
    properties:
      scriptService: %$ScriptGenieService
      
Director:
  rules:
    'scriptgenie': 'ScriptGenieController'
