---
Name: genie_admin_config
---
ModelAdmin:
  extensions:
    - GenieAdminExtension

Injector:
  GenieAdminExtension:
    properties:
      scriptService: %$GenieScriptService
      
Director:
  rules:
    'scriptgenie': 'ScriptGenieController'
